local fs = require("yalms.fs")
local helpers = require("yalms.helpers")

describe("yalms.fs", function()
  describe("json", function()
    before_each(function()
      helpers.mock_vim()
    end)

    after_each(function()
      helpers.unmock_vim()
    end)

    describe("encode", function()
      it("encodes table to json string", function()
        local result = fs.json.encode({ a = 1 })
        assert.is_string(result)
        assert.is_true(result:find("\"a\"") ~= nil)
        assert.is_true(result:find("1") ~= nil)
      end)

      it("encodes array", function()
        local result = fs.json.encode({ 1, 2, 3 })
        assert.is_string(result)
        assert.is_true(result:find("1") ~= nil)
        assert.is_true(result:find("2") ~= nil)
        assert.is_true(result:find("3") ~= nil)
      end)

      it("encodes string", function()
        local result = fs.json.encode("hello")
        assert.equal("\"hello\"", result)
      end)

      it("encodes boolean true", function()
        local result = fs.json.encode(true)
        assert.equal("true", result)
      end)

      it("encodes boolean false", function()
        local result = fs.json.encode(false)
        assert.equal("false", result)
      end)

      it("encodes nil", function()
        local result = fs.json.encode(nil)
        assert.equal("null", result)
      end)
    end)

    describe("decode", function()
      it("decodes json object", function()
        local result = fs.json.decode("{\"a\":1}")
        assert.equal(1, result.a)
      end)

      it("decodes array", function()
        local result = fs.json.decode("[1,2,3]")
        assert.equal(1, result[1])
        assert.equal(2, result[2])
        assert.equal(3, result[3])
      end)

      it("decodes string", function()
        local result = fs.json.decode("\"hello\"")
        assert.equal("hello", result)
      end)

      it("decodes boolean true", function()
        local result = fs.json.decode("true")
        assert.is_true(result)
      end)

      it("decodes boolean false", function()
        local result = fs.json.decode("false")
        assert.is_false(result)
      end)

      it("decodes null", function()
        local result = fs.json.decode("null")
        assert.is_nil(result)
      end)
    end)
  end)

  describe("write_file", function()
    it("writes and returns success", function()
      local path = "/tmp/yalms_test_write.txt"
      local ok, err = fs.write_file(path, "hello")
      assert.is_true(ok)
      assert.is_nil(err)
      os.remove(path)
    end)
  end)

  describe("read_file", function()
    it("reads existing file", function()
      local path = "/tmp/yalms_test_read.txt"
      local f = io.open(path, "w")
      f:write("hello")
      f:close()

      local content, err = fs.read_file(path)
      assert.equal("hello", content)
      assert.is_nil(err)
      os.remove(path)
    end)

    it("returns error for non-existing file", function()
      local content, err = fs.read_file("/tmp/yalms_nonexistent_12345.txt")
      assert.is_nil(content)
      assert.is_not_nil(err)
    end)
  end)
end)
