local json = require("yalms.json")
local helpers = require("helpers")

describe("yalms.json", function()
  before_each(function()
    helpers.mock_vim()
  end)

  after_each(function()
    helpers.unmock_vim()
  end)

  describe("encode", function()
    it("encodes table to json string", function()
      local result = json.encode({ a = 1 })
      assert.is_string(result)
      assert.is_true(result:find("\"a\"") ~= nil)
      assert.is_true(result:find("1") ~= nil)
    end)

    it("encodes array", function()
      local result = json.encode({ 1, 2, 3 })
      assert.is_string(result)
      assert.is_true(result:find("1") ~= nil)
      assert.is_true(result:find("2") ~= nil)
      assert.is_true(result:find("3") ~= nil)
    end)

    it("encodes string", function()
      local result = json.encode("hello")
      assert.equal("\"hello\"", result)
    end)

    it("encodes boolean true", function()
      local result = json.encode(true)
      assert.equal("true", result)
    end)

    it("encodes boolean false", function()
      local result = json.encode(false)
      assert.equal("false", result)
    end)

    it("encodes nil", function()
      local result = json.encode(nil)
      assert.equal("null", result)
    end)
  end)

  describe("decode", function()
    it("decodes json object", function()
      local result = json.decode("{\"a\":1}")
      assert.equal(1, result.a)
    end)

    it("decodes array", function()
      local result = json.decode("[1,2,3]")
      assert.equal(1, result[1])
      assert.equal(2, result[2])
      assert.equal(3, result[3])
    end)

    it("decodes string", function()
      local result = json.decode("\"hello\"")
      assert.equal("hello", result)
    end)

    it("decodes boolean true", function()
      local result = json.decode("true")
      assert.is_true(result)
    end)

    it("decodes boolean false", function()
      local result = json.decode("false")
      assert.is_false(result)
    end)

    it("decodes null", function()
      local result = json.decode("null")
      assert.is_nil(result)
    end)
  end)
end)
